"""add baseline_price to alerts

Revision ID: 6585e246d136
Revises: eabf2e1cc5d7
Create Date: 2026-07-02 22:59:27.704761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6585e246d136'
down_revision: Union[str, Sequence[str], None] = 'eabf2e1cc5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('baseline_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'baseline_price')
    # ### end Alembic commands ###
