"""add device_id to watchlist and alerts

Revision ID: aab001b11ab4
Revises: 6585e246d136
Create Date: 2026-07-28 17:47:18.631980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab001b11ab4'
down_revision: Union[str, Sequence[str], None] = '6585e246d136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('device_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.add_column('watchlist_symbols', sa.Column('device_id', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_watchlist_symbols_symbol'), table_name='watchlist_symbols')
    op.create_index(op.f('ix_watchlist_symbols_symbol'), 'watchlist_symbols', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_symbols_device_id'), 'watchlist_symbols', ['device_id'], unique=False)
    op.create_unique_constraint('uq_watchlist_symbols_device_symbol', 'watchlist_symbols', ['device_id', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watchlist_symbols_device_symbol', 'watchlist_symbols', type_='unique')
    op.drop_index(op.f('ix_watchlist_symbols_device_id'), table_name='watchlist_symbols')
    op.drop_index(op.f('ix_watchlist_symbols_symbol'), table_name='watchlist_symbols')
    op.create_index(op.f('ix_watchlist_symbols_symbol'), 'watchlist_symbols', ['symbol'], unique=True)
    op.drop_column('watchlist_symbols', 'device_id')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_column('alerts', 'device_id')
    # ### end Alembic commands ###
